# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "2ec1528bf4c0f5e2b386dd64b2e0691aee000be1"

[[deps.NearestNeighborsTest]]
path = "."
uuid = "1d4e4914-a46b-4e08-8d2f-7bc89898521c"
version = "1.0.0-DEV"
